export { AuthModule, AuthService } from './auth';
export { PermissionModule, PermissionService } from './permission';
export { PrismaModule, PrismaService } from './prisma';
export { ProjectsModule, ProjectsService } from './projects';
export { ShareModule, PasswordService } from './shared';
export { UserModule, UserService } from './user';
export { TicketsModule, TicketsService } from './tickets';
export { UploadModule } from './upload/upload.module';
export { FinanceModule } from './finance/finance.module';
export { MindMapModule } from './mind-maps/mind-maps.module';
export { AiModule } from './ai/ai.module';
export { AppConfigModule, AppConfigService } from './config/index';
export { ProgressModule } from './progress/progress.module';
export { EnglishLearningModule } from './english-learning/english-learning.module';
export { NotesModule } from './notes/notes.module';
export { CalendarModule } from './calendar/calendar.module';
